<a href="https://colab.research.google.com/github/wtryab/machinelearningpathway/blob/main/diabetesprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!kaggle datasets download akshaydattatraykhare/diabetes-dataset


Dataset URL: https://www.kaggle.com/datasets/akshaydattatraykhare/diabetes-dataset
License(s): CC0-1.0
  0% 0.00/8.91k [00:00<?, ?B/s]
100% 8.91k/8.91k [00:00<00:00, 14.0MB/s]


In [ ]:
from zipfile import ZipFile
file_name = "diabetes-dataset.zip"
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

Done


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/diabetes.csv")
data.head()
data.describe()
data.shape
data.value_counts("Outcome")
data.groupby("Outcome").mean()
data.isnull().sum()
data.isna().sum()
#We have to scale the data because look at the standard deviations so do that

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X = data.drop(columns = "Outcome", axis = 1)
Y = data["Outcome"]

In [ ]:
data.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [ ]:
scaler = StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns= X.columns)


In [ ]:
X

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.639947  0.848324       0.149641       0.907270 -0.692891  0.204013   
1      -0.844885 -1.123396      -0.160546       0.530902 -0.692891 -0.684422   
2       1.233880  1.943724      -0.263941      -1.288212 -0.692891 -1.103255   
3      -0.844885 -0.998208      -0.160546       0.154533  0.123302 -0.494043   
4      -1.141852  0.504055      -1.504687       0.907270  0.765836  1.409746   
..           ...       ...            ...            ...       ...       ...   
763     1.827813 -0.622642       0.356432       1.722735  0.870031  0.115169   
764    -0.547919  0.034598       0.046245       0.405445 -0.692891  0.610154   
765     0.342981  0.003301       0.149641       0.154533  0.279594 -0.735190   
766    -0.844885  0.159787      -0.470732      -1.288212 -0.692891 -0.240205   
767    -0.844885 -0.873019       0.046245       0.656358 -0.692891 -0.202129   

     DiabetesPedigreeFunction       Age  
0                    0.468492  1.425995  
1                   -0.365061 -0.190672  
2                    0.604397 -0.105584  
3                   -0.920763 -1.041549  
4                    5.484909 -0.020496  
..                        ...       ...  
763                 -0.908682  2.532136  
764                 -0.398282 -0.531023  
765                 -0.685193 -0.275760  
766                 -0.371101  1.170732  
767                 -0.473785 -0.871374  

[768 rows x 8 columns]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(614, 8)
(154, 8)
(614,)
(154,)


In [ ]:
Y_train.value_counts()
Y_test.value_counts()

Outcome
0    100
1     54
Name: count, dtype: int64

In [ ]:
model = svm.SVC(kernel = "linear")
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred = model.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

0.784370477568741
0.7792207792207793
[[46  4]
 [13 14]]
              precision    recall  f1-score   support

           0       0.78      0.92      0.84        50
           1       0.78      0.52      0.62        27

    accuracy                           0.78        77
   macro avg       0.78      0.72      0.73        77
weighted avg       0.78      0.78      0.77        77



In [ ]:
model = svm.SVC(kernel = "rbf")
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred = model.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

0.829232995658466
0.7142857142857143
[[42  8]
 [14 13]]
              precision    recall  f1-score   support

           0       0.75      0.84      0.79        50
           1       0.62      0.48      0.54        27

    accuracy                           0.71        77
   macro avg       0.68      0.66      0.67        77
weighted avg       0.70      0.71      0.70        77



In [ ]:
model = svm.SVC(kernel = "poly")
model.fit(X_train,Y_train)
print(model.score(X_train,Y_train))
Y_pred = model.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

0.8029315960912052
0.7077922077922078
[[93  7]
 [38 16]]
              precision    recall  f1-score   support

           0       0.71      0.93      0.81       100
           1       0.70      0.30      0.42        54

    accuracy                           0.71       154
   macro avg       0.70      0.61      0.61       154
weighted avg       0.70      0.71      0.67       154



In [ ]:
inputdata = (1,89,66,23,94,28.1,0.167,21)
inputdata_as_numpy_array = np.asarray(inputdata)
inputdata_reshaped = inputdata_as_numpy_array.reshape(1,-1)
scaledinput = StandardScaler().fit_transform(inputdata_reshaped)
prediction = model.predict(scaledinput)

if prediction[0] == 0:
  print("The person is not diabetic")
else:
  print("The person is diabetic")

The person is not diabetic


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
